#!/usr/bin/env python3

"""
Recon Framework - AI/ML Feature Extractor

Reads reconnaissance results generated by the Bash framework
and converts them into structured numerical features.

Usage:
    python3 ai/extract_features.py ctuniversity.com

Output:
    output/<domain>/ai/features.json
"""

import json
import re
import sys
from pathlib import Path
from collections import Counter
from urllib.parse import urlparse


# --------------------------------------------------
# Project Paths
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "output"


# --------------------------------------------------
# File Helpers
# --------------------------------------------------

def read_lines(path: Path):
    """Read a text file and return non-empty unique lines."""

    if not path.exists():
        return []

    try:
        with path.open("r", encoding="utf-8", errors="ignore") as file:
            return sorted({
                line.strip()
                for line in file
                if line.strip()
            })
    except OSError:
        return []


def count_lines(path: Path):
    """Count non-empty lines in a file."""

    return len(read_lines(path))


# --------------------------------------------------
# HTTPX Feature Extraction
# --------------------------------------------------

def parse_httpx(httpx_file: Path):
    """
    Extract useful information from HTTPX output.

    Example:
    https://example.com [200] [Title] [nginx] [Nginx]
    """

    lines = read_lines(httpx_file)

    status_codes = []
    technologies = []
    servers = []

    status_pattern = re.compile(r"\[(\d{3})\]")

    for line in lines:

        # Status code
        status_match = status_pattern.search(line)

        if status_match:
            status_codes.append(int(status_match.group(1)))

        # Extract bracketed fields
        fields = re.findall(r"\[([^\]]+)\]", line)

        if len(fields) >= 2:

            # Ignore the first field if it is the status code.
            for field in fields[1:]:

                field_lower = field.lower()

                if field_lower.startswith(("nginx", "apache", "cloudflare", "akamai")):
                    servers.append(field)

                elif field_lower not in {
                    "access denied",
                    "ok",
                    "moved permanently"
                }:
                    technologies.append(field)

    return {
        "live_http_count": len(lines),
        "http_status_distribution": dict(Counter(status_codes)),
        "technology_count": len(set(technologies)),
        "server_count": len(set(servers)),
    }


# --------------------------------------------------
# URL Features
# --------------------------------------------------

def parse_urls(url_file: Path):

    urls = read_lines(url_file)

    javascript_count = 0
    api_count = 0

    for url in urls:

        lower_url = url.lower()

        if lower_url.endswith(".js") or ".js?" in lower_url:
            javascript_count += 1

        if (
            "/api/" in lower_url
            or lower_url.startswith("https://api.")
            or lower_url.startswith("http://api.")
        ):
            api_count += 1

    return {
        "url_count": len(urls),
        "javascript_url_count": javascript_count,
        "api_url_count": api_count,
    }


# --------------------------------------------------
# Port Features
# --------------------------------------------------

def parse_ports(port_file: Path):

    lines = read_lines(port_file)

    ports = set()

    for line in lines:

        # Naabu normally produces:
        # example.com:443

        if ":" in line:

            try:
                port = line.rsplit(":", 1)[1]

                if port.isdigit():
                    ports.add(int(port))

            except (ValueError, IndexError):
                pass

    return {
        "open_port_count": len(lines),
        "unique_port_count": len(ports),
        "ports": sorted(ports),
    }


# --------------------------------------------------
# Nuclei Features
# --------------------------------------------------

def parse_nuclei(nuclei_file: Path):

    severity_counter = Counter()

    total_findings = 0

    if not nuclei_file.exists():
        return {
            "nuclei_total": 0,
            "nuclei_critical": 0,
            "nuclei_high": 0,
            "nuclei_medium": 0,
            "nuclei_low": 0,
            "nuclei_info": 0,
        }

    try:

        with nuclei_file.open(
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as file:

            for line in file:

                line = line.strip()

                if not line:
                    continue

                try:
                    finding = json.loads(line)

                except json.JSONDecodeError:
                    continue

                total_findings += 1

                severity = (
                    finding
                    .get("info", {})
                    .get("severity", "unknown")
                    .lower()
                )

                severity_counter[severity] += 1

    except OSError:
        pass

    return {
        "nuclei_total": total_findings,
        "nuclei_critical": severity_counter["critical"],
        "nuclei_high": severity_counter["high"],
        "nuclei_medium": severity_counter["medium"],
        "nuclei_low": severity_counter["low"],
        "nuclei_info": severity_counter["info"],
    }


# --------------------------------------------------
# Main Feature Extraction
# --------------------------------------------------

def extract_features(domain: str):

    workspace = OUTPUT_DIR / domain

    if not workspace.exists():
        raise FileNotFoundError(
            f"Workspace not found: {workspace}"
        )

    subdomains_dir = workspace / "subdomains"
    dns_dir = workspace / "dns"
    live_dir = workspace / "live"
    ports_dir = workspace / "ports"
    urls_dir = workspace / "urls"
    nuclei_dir = workspace / "nuclei"

    # ----------------------------------------------
    # Subdomain Features
    # ----------------------------------------------

    subfinder = read_lines(
        subdomains_dir / "subfinder.txt"
    )

    assetfinder = read_lines(
        subdomains_dir / "assetfinder.txt"
    )

    all_subdomains = read_lines(
        subdomains_dir / "all.txt"
    )

    # ----------------------------------------------
    # DNS Features
    # ----------------------------------------------

    resolved_hosts = read_lines(
        dns_dir / "resolved.txt"
    )

    # ----------------------------------------------
    # HTTPX Features
    # ----------------------------------------------

    httpx_features = parse_httpx(
        live_dir / "httpx.txt"
    )

    # ----------------------------------------------
    # URL Features
    # ----------------------------------------------

    live_urls = parse_urls(
        live_dir / "urls.txt"
    )

    katana_urls = parse_urls(
        urls_dir / "katana.txt"
    )

    # ----------------------------------------------
    # Port Features
    # ----------------------------------------------

    port_features = parse_ports(
        ports_dir / "naabu.txt"
    )

    # ----------------------------------------------
    # Nuclei Features
    # ----------------------------------------------

    nuclei_features = parse_nuclei(
        nuclei_dir / "findings.jsonl"
    )

    # ----------------------------------------------
    # Final Feature Vector
    # ----------------------------------------------

    features = {

        "target": domain,

        # Subdomains
        "subfinder_count": len(subfinder),
        "assetfinder_count": len(assetfinder),
        "subdomain_count": len(all_subdomains),

        # DNS
        "resolved_host_count": len(resolved_hosts),

        # HTTP
        "live_http_count": httpx_features[
            "live_http_count"
        ],

        "technology_count": httpx_features[
            "technology_count"
        ],

        "server_count": httpx_features[
            "server_count"
        ],

        # HTTP status distribution
        "http_status_distribution": httpx_features[
            "http_status_distribution"
        ],

        # Live URLs
        "live_url_count": live_urls[
            "url_count"
        ],

        # Katana
        "katana_url_count": katana_urls[
            "url_count"
        ],

        "javascript_url_count": (
            live_urls["javascript_url_count"]
            + katana_urls["javascript_url_count"]
        ),

        "api_url_count": (
            live_urls["api_url_count"]
            + katana_urls["api_url_count"]
        ),

        # Ports
        "open_port_count": port_features[
            "open_port_count"
        ],

        "unique_port_count": port_features[
            "unique_port_count"
        ],

        "ports": port_features["ports"],

        # Nuclei
        **nuclei_features,
    }

    return features


# --------------------------------------------------
# Save Features
# --------------------------------------------------

def save_features(domain: str, features: dict):

    output_dir = OUTPUT_DIR / domain / "ai"

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    output_file = output_dir / "features.json"

    with output_file.open(
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            features,
            file,
            indent=4
        )

    return output_file


# --------------------------------------------------
# CLI
# --------------------------------------------------

def main():

    if len(sys.argv) != 2:

        print(
            "Usage: python3 ai/extract_features.py <domain>"
        )

        sys.exit(1)

    domain = sys.argv[1].strip().lower()

    if not domain:

        print("[ERROR] Domain cannot be empty.")
        sys.exit(1)

    try:

        print(
            f"[INFO] Extracting features for {domain}"
        )

        features = extract_features(domain)

        output_file = save_features(
            domain,
            features
        )

        print(
            f"[SUCCESS] Features generated: {output_file}"
        )

    except FileNotFoundError as error:

        print(f"[ERROR] {error}")
        sys.exit(1)

    except Exception as error:

        print(
            f"[ERROR] Feature extraction failed: {error}"
        )

        sys.exit(1)


if __name__ == "__main__":
    main()
